### ISSUE TITLE
Constraining calculated angles to positive in wind.true2rel_dir function

### ISSUE THREAD

**Issue by mbrouet** [JonnoB/pyseatrials#5]
The wind.true2rel_dir function has a "constrain_to_positive" Boolean variable in the inputs, but this is never used in the code.

The same Boolean exists in the wind.rel2true_dir function, where it is used.

It would be great to implement this Boolean variable in both functions in the same way.

Regards,
Marius.

**Comment by JonnoB** [comment]
This should be fixed now

**Comment by mbrouet** [comment]
Hi Jonno.

Issue is not yet fixed, indeed the constrain_to_positive variable is now defaulted to "True" in both functions, but it is still not being used in the wind.true2rel_dir function.

This function uses the "find_gamma" function which can take constrain_to_positive as an input, but it isn't used within the function.

**Comment by JonnoB** [comment]
Fixed
